name: Scala CI

on:
  push:
    tags:
      - 'v*'
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
    - uses: sbt/setup-sbt@v1
    - name: Run tests
      shell: bash
      run: sbt test
